# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Keshuai\Documents\PSoC Creator\Workspace01\n00b.cydsn\n00b.cyprj
# Date: Wed, 25 Oct 2017 07:56:01 GMT
#set_units -time ns
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 13.888888888888888 -waveform {0 6.94444444444444} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 13.888888888888888 -waveform {0 6.94444444444444} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 7201 14401} [list [get_pins {ClockBlock/dclk_glb_0}]]


# Component constraints for C:\Users\Keshuai\Documents\PSoC Creator\Workspace01\n00b.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Keshuai\Documents\PSoC Creator\Workspace01\n00b.cydsn\n00b.cyprj
# Date: Wed, 25 Oct 2017 07:55:55 GMT
